### ISSUE TITLE
"commitsSince" not recognized

### ISSUE THREAD

**Issue by MGatner** [bmitch/churn-php#360] opened 2022-09-17 13:31 UTC
When I drop in the example config (modified or verbatim) I get the following warning on launch:
```console
Unrecognized configuration keys: commitsSince
```
Fresh install of `church` as `composer require --dev`, both pulled version `1.7.0`. I don't see any other reports of this so far; I will dig through the config code and bit and see if anything is apparent.

**Comment by MGatner** [comment] 2022-09-17 13:36
It is because the configuration string is actual the singular `commitSince`: https://github.com/bmitch/churn-php/blob/fca48716d5b958a3bd87ed80adefdf87e0e63f27/src/Configuration/Validator/CommitsSince.php#L20

The Validator is actually the plural though as well. Need a maintainer to advise, then I can send a PR one way or another.

**Comment by villfa** [comment] 2022-09-17 18:36
Thank you for the report!

The right key is `commitsSince`.
This regression exists since `1.6.0` and has been introduced by [1b59a42](https://github.com/bmitch/churn-php/commit/1b59a427afda35f93ca145f7c5afed010f9cbf6a).

In my opinion we should support the 2 spellings just in case some users already use the singular form.
However the usage of `commitSince` must trigger a deprecation message indicating it won't be supported in the next major version.

**Closed** 2022-09-18 18:33 UTC
Labels: bug

**Comment by villfa** [comment] 2022-09-18 19:03
FYI the fix has been released with [Churn 1.7.1](https://github.com/bmitch/churn-php/releases/tag/1.7.1) :)

**Comment by MGatner** [comment] 2022-09-19 10:25
🥳🎉🎊
